services:
  - type: web
    name: markee-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /
    autoDeploy: true 