services:
  - type: web
    name: markee-app
    env: node
    buildCommand: npm install --force && npm install react-scripts && npm run build
    startCommand: serve -s build
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
    healthCheckPath: /
    autoDeploy: true 